In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame(
    {
        "Name": [
            "Deepthi",
            "Sri",
            "Neha",
        ],
        "Age": [18, 19, 20],
        "Sex": ["Female", "Female", "Female"],
    }
)
df

      Name  Age     Sex
0  Deepthi   18  Female
1      Sri   19  Female
2     Neha   20  Female

In [4]:
df["Name"]

0    Deepthi
1        Sri
2       Neha
Name: Name, dtype: object

In [5]:
df["Age"].max()

20

In [6]:
df.describe()

        Age
count   3.0
mean   19.0
std     1.0
min    18.0
25%    18.5
50%    19.0
75%    19.5
max    20.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Sex     3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [8]:
data = pd.Series([10, 20, 30, 40, 50])

print(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
df = pd.DataFrame({
    "Name": ["Ram", "Shyam", "Mohan"],
    "Marks": [80, 95, 70]
})

print(df.sort_values("Marks"))

    Name  Marks
2  Mohan     70
0    Ram     80
1  Shyam     95